from pathlib import Path
from dataclasses import dataclass, asdict
from typing import List
import time
import json
import logging
import requests
from lxml import etree as ET

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--arxiv_id", type=str, required=False, default=None)
args = parser.parse_args()

ATOM_NAMESPACE = "http://www.w3.org/2005/Atom"
SOURCE_PAPERS_PATH = Path(__file__).parent.parent / "configs" / "source_papers.json"

@dataclass
class Paper:
    arxiv_id: str
    title: str | None = None
    abstract: str | None = None
    authors: List[str] | None = None

def parse_from_arxiv(arxiv_id: str) -> Paper:
    """
    Parse paper information from arXiv API given an arXiv id
    TODO: Generated by Cursor. Reviews required.
    """
    api_url = f"http://export.arxiv.org/api/query?id_list={arxiv_id}"
    try:
        response = requests.get(api_url)
        if response.status_code == 200:
            # parse XML
            root = ET.fromstring(response.content)
            # arXiv returns entry under 'entry' tag
            entry = root.find(f"{{{ATOM_NAMESPACE}}}entry")
            try:
                title = entry.find(f"{{{ATOM_NAMESPACE}}}title")
                title = title.text.strip() if title is not None else None

                abstract = entry.find(f"{{{ATOM_NAMESPACE}}}summary")
                if abstract is not None:
                    abstract = abstract.text.strip()
                else:
                    abstract = None
                
                authors = []
                for author in entry.findall(f"{{{ATOM_NAMESPACE}}}author"):
                    name = author.find(f"{{{ATOM_NAMESPACE}}}name")
                    if name is not None:
                        authors.append(name.text)

                return Paper(
                    arxiv_id=arxiv_id,
                    title=title,
                    abstract=abstract,
                    authors=authors if authors else None
                )
            except Exception as e:
                raise Exception(f"Parsing paper from arXiv API has successed.\
                    However, failed to parse paper information: {str(e)}")
        else:
            raise Exception(f"Parsing paper from arXiv API has failed. \
                Status code: {response.status_code}. Response: {response.text}")
    except Exception as e:
        raise Exception(f"Unexpected error when parsing paper from arXiv API. \
            Error message: {str(e)}")

if __name__ == "__main__":
    updated_papers = []

    if args.arxiv_id:
        paper = parse_from_arxiv(args.arxiv_id)
        updated_papers.append(asdict(paper))
    else:
        with open(SOURCE_PAPERS_PATH, "r", encoding="utf-8") as f:
            papers = json.load(f)

        logging.info(f"Parsing {len(papers)} papers from arXiv API...")
        
        for paper in papers:
            arxiv_id = paper.get("arxiv_id")
            if not arxiv_id:
                logging.warning(f"Missing arXiv ID in paper {paper}.")
                continue

            paper = parse_from_arxiv(arxiv_id)
            updated_papers.append(asdict(paper))
            time.sleep(1) # c

    with open(SOURCE_PAPERS_PATH, "w", encoding="utf-8") as f:
        json.dump(updated_papers, f, ensure_ascii=False, indent=4)

    logging.info(f"Parsed {len(updated_papers)} papers from arXiv API.")

